/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppBar: typeof import('./components/layout/AppBar.vue')['default']
    AppFooter: typeof import('./components/layout/AppFooter.vue')['default']
    AppSnackbar: typeof import('./components/layout/AppSnackbar.vue')['default']
    BlogCardLarge: typeof import('./components/blog/BlogCardLarge.vue')['default']
    BlogCardSmall: typeof import('./components/blog/BlogCardSmall.vue')['default']
    BlogDeleteDialog: typeof import('./components/blog/BlogDeleteDialog.vue')['default']
    BlogEmptyPlaceholder: typeof import('./components/blog/BlogEmptyPlaceholder.vue')['default']
    BlogForm: typeof import('./components/blog/BlogForm.vue')['default']
    BlogGenerateDialog: typeof import('./components/blog/BlogGenerateDialog.vue')['default']
    NotFound: typeof import('./components/common/NotFound.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
